config/routes.rb
Rails.application.routes.draw do
  get 'new', as: 'new', to: 'games#new'
  get 'score', as: 'score', to: 'games#score'
  post 'score', to: 'games#score'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @letters = []
    alphabet = ('A'..'Z').to_a
    10.times do
      @letters << alphabet.sample
    end
  end

  def score
    @word = params['word']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>Games#new</h1>

<button id="start-game">Start Game</button>

<p id="stop-time"></p>

<div id="game" class="hidden">
  <ul class="inline-list">
    <% @letters.each do |letter| %>
      <li><%= letter %></li>
    <% end %>
  </ul>

  <form action="<%= score_path %>" class="games-form" method="POST">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <input type="text" name="word">
    <input type="submit">
  </form>
</div>

app/views/games/score.html.erb
<h1>Games#score</h1>
<p>Find me in app/views/games/score.html.erb</p>

<p>Your word was: "<%= @word %>"</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>